[package]
name = "rusty-visuals"
version = "0.1.0"
authors = ["Arjun Puri <arjunpur2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14"
rand = "0.7.3"
itertools = "0.9.0"

[[bin]]
name="waves"
path="src/waves.rs"

[[bin]]
name="random_walk"
path="src/randomwalk.rs"

[[bin]]
name="two_dim_perlin"
path="src/two-dimensional-perlin.rs"

[[bin]]
name="vectors"
path="src/vectors/main.rs"

[[bin]]
name="up_down_car"
path="src/vectors/up_down_car.rs"

[[bin]]
name="ecosystem"
path="src/ecosystem/main.rs"
