[package]
name = "rusty-visuals"
version = "0.1.0"
authors = ["Arjun Puri <arjunpur2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14"
